/**
 * Fixture data for `npm run seed`. Moved out of src/lib/data/* when those
 * modules became live Supabase reads — kept here so seeding a fresh project
 * stays a one-command, DB-independent operation.
 */
import type { Account, Order, SavedAssortment, Style } from "../src/lib/types";

/** Seed fixtures don't set availableBoxTypes/primaryImageUrl — the DB column defaults to all 3 boxes. */
type SeedStyle = Omit<Style, "availableBoxTypes" | "primaryImageUrl">;

const STANDARD_BREAKS = [
  { minUnits: 1, multiplier: 1 },
  { minUnits: 12, multiplier: 0.95 },
  { minUnits: 36, multiplier: 0.9 },
];

const DEEP_BREAKS = [
  { minUnits: 1, multiplier: 1 },
  { minUnits: 12, multiplier: 0.94 },
  { minUnits: 24, multiplier: 0.9 },
  { minUnits: 48, multiplier: 0.85 },
];

export const STYLES: SeedStyle[] = [
  {
    id: "st-01",
    slug: "meridian-84",
    styleNumber: "HR-1001",
    name: "Meridian '84",
    category: "running",
    gender: "unisex",
    availability: "available",
    tagline: "The flagship. Unchanged silhouette since the '84 trials.",
    description:
      "The style that put Hector on the starting line. A full-grain suede and ripstop nylon upper over the original wedge-cupsole geometry, resoled in a modern high-rebound EVA. Retailers reorder this one on a schedule.",
    materials: ["Full-grain suede", "Ripstop nylon", "High-rebound EVA midsole", "Carbon rubber outsole"],
    colorways: [
      { id: "c1", name: "Cinder / Chalk", swatch: ["#6b6560", "#e4e1d9"], skuSuffix: "CIN" },
      { id: "c2", name: "Signal Navy", swatch: ["#1e2a4a", "#e4e1d9"], skuSuffix: "NVY" },
      { id: "c3", name: "Track Red", swatch: ["#a13322", "#1a1d22"], skuSuffix: "RED" },
      { id: "c4", name: "Bone", swatch: ["#e9e4d8", "#a9a39a"], skuSuffix: "BON" },
    ],
    basePrice: 42,
    msrp: 110,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 3,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 10.4,
    lastNote: "Reorders fastest in Cinder/Chalk. Keep 12+ deep on standing orders.",
  },
  {
    id: "st-02",
    slug: "trackman-low",
    styleNumber: "HR-1014",
    name: "Trackman Low",
    category: "running",
    gender: "mens",
    availability: "available",
    tagline: "The training shoe built for the guys who log the miles.",
    description:
      "A daily trainer with a firmer dual-density midsole and a mesh upper reinforced at the lateral break-point. Built for stores that serve run clubs, not just runway.",
    materials: ["Engineered mesh", "TPU cage", "Dual-density EVA", "Blown rubber outsole"],
    colorways: [
      { id: "c1", name: "Graphite", swatch: ["#3a3d43", "#6b6560"], skuSuffix: "GRA" },
      { id: "c2", name: "Signal / White", swatch: ["#1e48b8", "#ffffff"], skuSuffix: "SIG" },
      { id: "c3", name: "Olive Field", swatch: ["#5c5c3f", "#e4e1d9"], skuSuffix: "OLV" },
    ],
    basePrice: 38,
    msrp: 95,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 9.8,
    lastNote: "Strong sell-through with run-specialty accounts near college towns.",
  },
  {
    id: "st-03",
    slug: "vantage-runner",
    styleNumber: "HR-1022",
    name: "Vantage Runner",
    category: "running",
    gender: "womens",
    availability: "available",
    tagline: "Women's last, tuned narrower through the midfoot.",
    description:
      "Built on a dedicated women's last rather than a downsized men's mold. Same wedge-cupsole DNA as the Meridian, refined for a narrower midfoot and lower volume forefoot.",
    materials: ["Suede overlays", "Perforated nylon", "High-rebound EVA midsole", "Carbon rubber outsole"],
    colorways: [
      { id: "c1", name: "Chalk / Cinder", swatch: ["#e4e1d9", "#6b6560"], skuSuffix: "CHK" },
      { id: "c2", name: "Court Yellow", swatch: ["#e8b400", "#1a1d22"], skuSuffix: "CYL" },
      { id: "c3", name: "Merlot", swatch: ["#5c2030", "#e4e1d9"], skuSuffix: "MER" },
    ],
    basePrice: 42,
    msrp: 110,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 3,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 8.9,
    lastNote: "Court Yellow is a top-3 seller across every account this season.",
  },
  {
    id: "st-04",
    slug: "interval-sc",
    styleNumber: "HR-1030",
    name: "Interval SC",
    category: "running",
    gender: "unisex",
    availability: "prebook",
    shipWindow: "Ships March 2027",
    tagline: "Suede classic. Built for the lifestyle wall, not the track.",
    description:
      "A lower-profile lifestyle read on the archive Interval trainer — full suede upper, gum outsole, minimal branding. This is the shoe for accounts building a heritage running wall.",
    materials: ["Full suede upper", "Foam-backed collar", "EVA wedge midsole", "Gum rubber outsole"],
    colorways: [
      { id: "c1", name: "Cinder", swatch: ["#6b6560", "#c9a06a"], skuSuffix: "CIN" },
      { id: "c2", name: "Ink", swatch: ["#1a1d22", "#c9a06a"], skuSuffix: "INK" },
    ],
    basePrice: 39,
    msrp: 100,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 10.1,
    lastNote: "Pre-book only — limited suede allocation confirmed with mill for spring.",
  },
  {
    id: "st-05",
    slug: "relay-mid",
    styleNumber: "HR-1041",
    name: "Relay Mid",
    category: "running",
    gender: "unisex",
    availability: "available",
    tagline: "A mid-cut trainer for cold-weather run specialty.",
    description:
      "Same platform as the Trackman with an added ankle collar and water-resistant nylon upper for accounts in cold-weather markets.",
    materials: ["Water-resistant ripstop", "Neoprene collar", "Dual-density EVA", "Lugged rubber outsole"],
    colorways: [
      { id: "c1", name: "Ink / Cinder", swatch: ["#1a1d22", "#6b6560"], skuSuffix: "INK" },
      { id: "c2", name: "Ember", swatch: ["#c1451e", "#1a1d22"], skuSuffix: "EMB" },
    ],
    basePrice: 44,
    msrp: 115,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["preferred", "vip"],
    weightOz: 11.6,
    lastNote: "Preferred tier and above only this season — allocation is tight.",
  },
  {
    id: "st-06",
    slug: "pace-setter",
    styleNumber: "HR-1055",
    name: "Pace Setter",
    category: "running",
    gender: "unisex",
    availability: "available",
    tagline: "The value-tier opener for growing accounts.",
    description:
      "A simplified construction of the Trackman platform at an accessible price point — the shoe new accounts use to test sell-through before committing to deeper buys.",
    materials: ["Mesh upper", "Single-density EVA", "Rubber outsole"],
    colorways: [
      { id: "c1", name: "Chalk", swatch: ["#e4e1d9", "#a9a39a"], skuSuffix: "CHK" },
      { id: "c2", name: "Ink", swatch: ["#1a1d22", "#6b6560"], skuSuffix: "INK" },
      { id: "c3", name: "Signal", swatch: ["#1e48b8", "#e4e1d9"], skuSuffix: "SIG" },
    ],
    basePrice: 29,
    msrp: 75,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 1,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 9.4,
    lastNote: "Lowest MOQ in the line — good opener for a new account's first PO.",
  },
  {
    id: "st-07",
    slug: "baseline-pro",
    styleNumber: "HC-2001",
    name: "Baseline Pro",
    category: "court",
    gender: "unisex",
    availability: "available",
    tagline: "The original '84 court silhouette, rebuilt for concrete.",
    description:
      "Leather court shoe with a herringbone outsole pattern lifted from the original 1984 mold. Reads as a lifestyle shoe, performs as a court shoe.",
    materials: ["Full-grain leather", "Herringbone rubber outsole", "EVA sockliner"],
    colorways: [
      { id: "c1", name: "Bone / Ink", swatch: ["#e9e4d8", "#1a1d22"], skuSuffix: "BON" },
      { id: "c2", name: "Signal Navy", swatch: ["#1e2a4a", "#e9e4d8"], skuSuffix: "NVY" },
      { id: "c3", name: "Court Yellow", swatch: ["#e8b400", "#1a1d22"], skuSuffix: "CYL" },
      { id: "c4", name: "Ember", swatch: ["#c1451e", "#e9e4d8"], skuSuffix: "EMB" },
    ],
    basePrice: 41,
    msrp: 105,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 3,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 12.2,
    lastNote: "Best sell-through of any court style. Reorder cadence is roughly 8 weeks.",
  },
  {
    id: "st-08",
    slug: "match-point",
    styleNumber: "HC-2012",
    name: "Match Point",
    category: "court",
    gender: "unisex",
    availability: "available",
    tagline: "Tennis-specific, built to outlast a season on hard court.",
    description:
      "A performance tennis build with a reinforced toe cap and a modified herringbone pattern for lateral grip. Sold into tennis specialty and resort pro shops.",
    materials: ["Synthetic leather", "Reinforced toe cap", "PU midsole", "Durable rubber outsole"],
    colorways: [
      { id: "c1", name: "Chalk / Signal", swatch: ["#e4e1d9", "#1e48b8"], skuSuffix: "CHK" },
      { id: "c2", name: "Ink", swatch: ["#1a1d22", "#a9a39a"], skuSuffix: "INK" },
    ],
    basePrice: 37,
    msrp: 95,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 11.8,
    lastNote: "Toe-cap durability is the sell-in story — lead with that on the floor.",
  },
  {
    id: "st-09",
    slug: "volley-84",
    styleNumber: "HC-2020",
    name: "Volley '84",
    category: "court",
    gender: "womens",
    availability: "available",
    tagline: "The archive volleyball shoe, reissued.",
    description:
      "A low-top volleyball build from the archive, reissued on the women's last with a canvas-and-leather mix and gum outsole.",
    materials: ["Canvas", "Leather overlays", "EVA midsole", "Gum rubber outsole"],
    colorways: [
      { id: "c1", name: "Bone", swatch: ["#e9e4d8", "#c9a06a"], skuSuffix: "BON" },
      { id: "c2", name: "Merlot", swatch: ["#5c2030", "#e9e4d8"], skuSuffix: "MER" },
      { id: "c3", name: "Ink", swatch: ["#1a1d22", "#c9a06a"], skuSuffix: "INK" },
    ],
    basePrice: 34,
    msrp: 88,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 9.1,
    lastNote: "Skews lifestyle — carried well outside of team-sport accounts last season.",
  },
  {
    id: "st-10",
    slug: "deuce-court",
    styleNumber: "HC-2033",
    name: "Deuce Court",
    category: "court",
    gender: "unisex",
    availability: "prebook",
    shipWindow: "Ships January 2027",
    tagline: "A cleaner, minimal read on Baseline Pro.",
    description:
      "Strips the Baseline Pro down to a single-material canvas upper with a vulcanized construction for a lower price point and a cleaner silhouette.",
    materials: ["Canvas upper", "Vulcanized rubber construction"],
    colorways: [
      { id: "c1", name: "Chalk", swatch: ["#e4e1d9", "#a9a39a"], skuSuffix: "CHK" },
      { id: "c2", name: "Ink", swatch: ["#1a1d22", "#6b6560"], skuSuffix: "INK" },
    ],
    basePrice: 27,
    msrp: 70,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 1,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 10.8,
    lastNote: "Pre-book cutoff is tight — confirm quantities before the mill locks in November.",
  },
  {
    id: "st-11",
    slug: "sideline-high",
    styleNumber: "HC-2041",
    name: "Sideline High",
    category: "court",
    gender: "mens",
    availability: "available",
    tagline: "High-top basketball archive build.",
    description:
      "A high-top basketball silhouette from the archive with a padded collar and leather-and-nylon upper. Carried mostly by heritage basketball and streetwear accounts.",
    materials: ["Leather", "Ballistic nylon", "Padded collar", "EVA midsole"],
    colorways: [
      { id: "c1", name: "Ink / Court Yellow", swatch: ["#1a1d22", "#e8b400"], skuSuffix: "INK" },
      { id: "c2", name: "Bone", swatch: ["#e9e4d8", "#1a1d22"], skuSuffix: "BON" },
      { id: "c3", name: "Signal Navy", swatch: ["#1e2a4a", "#e8b400"], skuSuffix: "NVY" },
    ],
    basePrice: 45,
    msrp: 118,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 13.5,
    lastNote: "Ink / Court Yellow is the account favorite for window display.",
  },
  {
    id: "st-12",
    slug: "ridgeline-gtx",
    styleNumber: "HT-3001",
    name: "Ridgeline GTX",
    category: "trail",
    gender: "unisex",
    availability: "available",
    tagline: "Waterproof trail runner for four-season accounts.",
    description:
      "A GORE-TEX-lined trail build with a lugged, multi-directional outsole and a rock plate underfoot. The technical anchor of the trail range.",
    materials: ["GORE-TEX membrane", "Ripstop nylon", "TPU rock plate", "Multi-directional lugged outsole"],
    colorways: [
      { id: "c1", name: "Olive / Cinder", swatch: ["#5c5c3f", "#6b6560"], skuSuffix: "OLV" },
      { id: "c2", name: "Ink / Ember", swatch: ["#1a1d22", "#c1451e"], skuSuffix: "INK" },
    ],
    basePrice: 54,
    msrp: 140,
    priceBreaks: DEEP_BREAKS,
    moqBoxes: 3,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 12.9,
    lastNote: "Deep price breaks reward accounts that buy the full run at once.",
  },
  {
    id: "st-13",
    slug: "summit-trainer",
    styleNumber: "HT-3010",
    name: "Summit Trainer",
    category: "trail",
    gender: "unisex",
    availability: "prebook",
    shipWindow: "Ships April 2027",
    tagline: "Lightweight trail trainer for fastpacking accounts.",
    description:
      "A lighter, more flexible trail build for accounts serving fastpacking and trail-running customers rather than full backcountry.",
    materials: ["Air-mesh upper", "EVA midsole", "Sticky rubber outsole"],
    colorways: [
      { id: "c1", name: "Cinder", swatch: ["#6b6560", "#e4e1d9"], skuSuffix: "CIN" },
      { id: "c2", name: "Ember / Ink", swatch: ["#c1451e", "#1a1d22"], skuSuffix: "EMB" },
    ],
    basePrice: 46,
    msrp: 120,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 10.6,
    lastNote: "New for the trail range — sell as a companion to Ridgeline GTX.",
  },
  {
    id: "st-14",
    slug: "traverse-low",
    styleNumber: "HT-3022",
    name: "Traverse Low",
    category: "trail",
    gender: "unisex",
    availability: "available",
    tagline: "Everyday hiking shoe with trail-runner comfort.",
    description:
      "A low-cut hiker that borrows its midsole from the Ridgeline GTX but drops the waterproof membrane for accounts in warmer, drier markets.",
    materials: ["Suede and mesh upper", "EVA midsole", "Lugged rubber outsole"],
    colorways: [
      { id: "c1", name: "Bone / Cinder", swatch: ["#e9e4d8", "#6b6560"], skuSuffix: "BON" },
      { id: "c2", name: "Olive", swatch: ["#5c5c3f", "#1a1d22"], skuSuffix: "OLV" },
      { id: "c3", name: "Signal Navy", swatch: ["#1e2a4a", "#e9e4d8"], skuSuffix: "NVY" },
    ],
    basePrice: 43,
    msrp: 112,
    priceBreaks: STANDARD_BREAKS,
    moqBoxes: 2,
    tierEligibility: ["standard", "preferred", "vip"],
    weightOz: 11.2,
    lastNote: "Carries well as a year-round hiker in warm-climate markets.",
  },
];

export const ACCOUNTS: Account[] = [
  {
    id: "acct-001",
    businessName: "Union Supply Co.",
    contactName: "Dana Ferris",
    email: "buyer@unionsupply.com",
    password: "wholesale84",
    tier: "preferred",
    status: "active",
    creditTerms: "net30",
    creditLimit: 45000,
    resaleCertId: "OR-RS-88214",
    businessType: "Multi-brand run specialty (2 doors)",
    storeLocation: "Portland, OR",
    expectedVolume: "$40,000–$75,000 / year",
    appliedAt: "2025-11-03",
    approvedAt: "2025-11-06",
    role: "buyer",
    shipTo: [
      {
        id: "ship-1",
        label: "Union Supply — Hawthorne",
        line1: "4110 SE Hawthorne Blvd",
        city: "Portland",
        state: "OR",
        zip: "97214",
        isDefault: true,
      },
      {
        id: "ship-2",
        label: "Union Supply — Distribution Annex",
        line1: "8800 NE Alderwood Rd, Suite C",
        city: "Portland",
        state: "OR",
        zip: "97220",
      },
    ],
    rep: {
      name: "Marcus Iyer",
      title: "Territory Sales Manager, Pacific NW",
      email: "marcus.iyer@hector1984.com",
      phone: "(503) 555-0148",
      initials: "MI",
      territory: "WA / OR / ID",
    },
  },
  {
    id: "acct-002",
    businessName: "Fieldhouse Athletics",
    contactName: "Priya Nandakumar",
    email: "buyer@fieldhouseath.com",
    password: "wholesale84",
    tier: "vip",
    status: "active",
    creditTerms: "net60",
    creditLimit: 120000,
    resaleCertId: "IL-RS-40217",
    businessType: "Regional chain (6 doors)",
    storeLocation: "Chicago, IL",
    expectedVolume: "$150,000+ / year",
    appliedAt: "2024-02-11",
    approvedAt: "2024-02-14",
    role: "buyer",
    shipTo: [
      {
        id: "ship-1",
        label: "Fieldhouse — DC Chicago",
        line1: "2200 S Ashland Ave",
        city: "Chicago",
        state: "IL",
        zip: "60608",
        isDefault: true,
      },
    ],
    rep: {
      name: "Renata Souza",
      title: "Key Account Director",
      email: "renata.souza@hector1984.com",
      phone: "(312) 555-0193",
      initials: "RS",
      territory: "National Accounts",
    },
  },
  {
    id: "acct-003",
    businessName: "Trailhead Mercantile",
    contactName: "Owen Bright",
    email: "buyer@trailheadmerc.com",
    password: "wholesale84",
    tier: "standard",
    status: "active",
    creditTerms: "prepay",
    creditLimit: 8000,
    resaleCertId: "CO-RS-11209",
    businessType: "Independent outdoor specialty (1 door)",
    storeLocation: "Bend, OR",
    expectedVolume: "$10,000–$25,000 / year",
    appliedAt: "2026-05-19",
    approvedAt: "2026-05-24",
    role: "buyer",
    shipTo: [
      {
        id: "ship-1",
        label: "Trailhead Mercantile",
        line1: "119 NW Newport Ave",
        city: "Bend",
        state: "OR",
        zip: "97703",
        isDefault: true,
      },
    ],
    rep: {
      name: "Marcus Iyer",
      title: "Territory Sales Manager, Pacific NW",
      email: "marcus.iyer@hector1984.com",
      phone: "(503) 555-0148",
      initials: "MI",
      territory: "WA / OR / ID",
    },
  },
];

/** Order history for acct-001 (Union Supply Co.) — the demo login account. */
export const ORDERS: Record<string, Order[]> = {
  "acct-001": [
    {
      id: "ORD-59090",
      poNumber: "US-0522",
      placedAt: "2026-07-25",
      status: "submitted",
      terms: "net30",
      shipToId: "ship-1",
      notes: "Please hold for combined ship with any Interval SC backorder.",
      lines: [
        { styleId: "st-01", colorwayId: "c1", boxTypeId: "box10", qty: 2, unitPrice: 37.11 },
      ],
    },
    {
      id: "ORD-59012",
      poNumber: "US-0514",
      placedAt: "2026-07-20",
      status: "in_production",
      terms: "net30",
      shipToId: "ship-1",
      lines: [
        { styleId: "st-04", colorwayId: "c1", boxTypeId: "box8", qty: 2, unitPrice: 34.68 },
      ],
      invoiceUrl: "#",
    },
    {
      id: "ORD-58877",
      poNumber: "US-0501",
      placedAt: "2026-07-10",
      status: "shipped",
      terms: "net30",
      shipToId: "ship-2",
      lines: [
        { styleId: "st-07", colorwayId: "c1", boxTypeId: "box8", qty: 1, unitPrice: 36.44 },
        { styleId: "st-07", colorwayId: "c1", boxTypeId: "box10", qty: 1, unitPrice: 36.44 },
        { styleId: "st-07", colorwayId: "c3", boxTypeId: "box12", qty: 1, unitPrice: 36.44 },
      ],
      invoiceUrl: "#",
    },
    {
      id: "ORD-58210",
      poNumber: "US-0472",
      placedAt: "2026-06-02",
      status: "delivered",
      terms: "net30",
      shipToId: "ship-1",
      lines: [
        { styleId: "st-01", colorwayId: "c1", boxTypeId: "box10", qty: 1, unitPrice: 37.11 },
        { styleId: "st-01", colorwayId: "c1", boxTypeId: "box12", qty: 1, unitPrice: 37.11 },
        { styleId: "st-01", colorwayId: "c2", boxTypeId: "box10", qty: 1, unitPrice: 37.11 },
        { styleId: "st-02", colorwayId: "c2", boxTypeId: "box8", qty: 1, unitPrice: 33.54 },
        { styleId: "st-02", colorwayId: "c2", boxTypeId: "box10", qty: 1, unitPrice: 33.54 },
      ],
      invoiceUrl: "#",
    },
  ],
  "acct-002": [
    {
      id: "ORD-57110",
      poNumber: "FH-2291",
      placedAt: "2026-07-15",
      status: "shipped",
      terms: "net60",
      shipToId: "ship-1",
      lines: [
        { styleId: "st-11", colorwayId: "c1", boxTypeId: "box12", qty: 3, unitPrice: 35.96 },
      ],
      invoiceUrl: "#",
    },
  ],
  "acct-003": [
    {
      id: "ORD-59201",
      poNumber: "TM-0031",
      placedAt: "2026-07-24",
      status: "submitted",
      terms: "prepay",
      shipToId: "ship-1",
      lines: [
        { styleId: "st-14", colorwayId: "c1", boxTypeId: "box8", qty: 1, unitPrice: 43 },
      ],
    },
  ],
};

export const ASSORTMENTS: Record<string, SavedAssortment[]> = {
  "acct-001": [
    {
      id: "asrt-1",
      name: "Fall Reorder Wall",
      createdAt: "2026-06-15",
      styleIds: ["st-01", "st-07", "st-02"],
    },
    {
      id: "asrt-2",
      name: "New Door Opener Kit",
      createdAt: "2026-07-01",
      styleIds: ["st-06", "st-10", "st-09"],
    },
  ],
  "acct-002": [
    {
      id: "asrt-1",
      name: "Flagship Store Reset",
      createdAt: "2026-05-20",
      styleIds: ["st-11", "st-07", "st-12", "st-01"],
    },
  ],
  "acct-003": [],
};
